workflows:
  android-expo:
    name: Android Expo Build
    max_build_duration: 60
    instance_type: mac_m1 # Use mac_m1 or standard depending on your plan
    environment:
      vars:
        EXPO_TOKEN: Encrypted(...) # optional, if you want to login automatically
      flutter: stable
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli
          npm install
      - name: Prebuild (optional)
        script: |
          npx expo prebuild --no-install
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - kadeshemmanuel@gmail.com
      codemagic:
        notify_on_build_failed: true
        notify_on_build_succeeded: true
    triggers:
      - push
      - pull_request
