workflows:
  android-expo:
    name: Android Expo Build
    max_build_duration: 60
    instance_type: linux
    environment:
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli
          npm install
      - name: Prebuild (optional)
        script: |
          npx expo prebuild --no-install
      - name: Build APK
        script: |
          npx expo build:android -t apk
    artifacts:
      - '**/*.apk'
